### ISSUE TITLE
Error when compile with version : 0.10.1 - ubuntu

### ISSUE THREAD

**Issue by linuxpham** [tikv/grpc-rs#570]
**Describe the bug**

Os : ubuntu
Cmake : cmake version 3.16.3
Gcc: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

Can not link with version: 0.10.1 on ubuntu  (macOS is OK)

multiple definition of `grpcwrap_server_request_call'; /source/target/x86_64-unknown-linux-gnu/release/deps/libgrpcio_sys-9ea061c418085455.rlib(grpc_wrap.o):grpc_wrap.cc:(.text.grpcwrap_server_request_call+0x0): first defined here

**To Reproduce**
 1. Vesion 0.9.1 => compile OK
 2. change to 0.10.1
 3. Can not compile on Ubuntu

**Comment by linuxpham** [comment]
![Screen Shot 2022-04-15 at 20 19 52](https://user-images.githubusercontent.com/154762/163575609-c619a010-e8f5-4be2-86eb-904cb122edd1.png)

**Comment by BusyJay** [comment]
You are mixing different version of the crates. `grep -A 1 'name = "grpcio-sys"' Cargo.lock` should show at least two different results.

**Comment by linuxpham** [comment]
Yes, it is a problem with the `Cargo.lock` . Thank you so much !
